[package]
name = "wifilog"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
rusqlite = "0.33.0"
subprocess = "0.2"
tokio = { version = "1", features = ["time", "macros", "rt-multi-thread"] }
